/**
 * Shared email template components.
 * All HTML is table-based with inline styles for maximum email client compatibility.
 */

// --- Color palette (matching the app's dark theme for branding) ---

const colors = {
  bg: "#f4f4f5",
  cardBg: "#ffffff",
  headerBg: "#18181b",
  headerText: "#ffffff",
  text: "#27272a",
  textMuted: "#71717a",
  textLight: "#a1a1aa",
  border: "#e4e4e7",
  accent: "#f97316",
  success: "#10b981",
  warning: "#eab308",
  danger: "#ef4444",
  info: "#3b82f6",
};

// --- Layout components ---

export function emailWrapper(title: string, content: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
</head>
<body style="margin:0;padding:0;background:${colors.bg};font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;-webkit-font-smoothing:antialiased;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${colors.bg};">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
          ${content}
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export function emailHeader(title: string, subtitle: string): string {
  return `<tr>
  <td style="background:${colors.headerBg};padding:24px 32px;border-radius:8px 8px 0 0;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td>
          <span style="color:${colors.accent};font-size:14px;font-weight:700;letter-spacing:0.5px;">CF-REPORTING</span>
        </td>
      </tr>
      <tr>
        <td style="padding-top:12px;">
          <h1 style="margin:0;color:${colors.headerText};font-size:22px;font-weight:700;">${escapeHtml(title)}</h1>
        </td>
      </tr>
      <tr>
        <td style="padding-top:4px;">
          <span style="color:${colors.textLight};font-size:13px;">${escapeHtml(subtitle)}</span>
        </td>
      </tr>
    </table>
  </td>
</tr>`;
}

export function emailFooter(dashboardUrl?: string): string {
  const now = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit", timeZoneName: "short",
  });

  return `<tr>
  <td style="padding:20px 32px;border-top:1px solid ${colors.border};background:${colors.cardBg};border-radius:0 0 8px 8px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      ${dashboardUrl ? `<tr><td align="center" style="padding-bottom:16px;">
        <a href="${escapeHtml(dashboardUrl)}" style="display:inline-block;padding:10px 24px;background:${colors.accent};color:#fff;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600;">View Full Report</a>
      </td></tr>` : ""}
      <tr>
        <td align="center" style="color:${colors.textLight};font-size:11px;">
          Generated by cf-reporting on ${escapeHtml(now)}
        </td>
      </tr>
    </table>
  </td>
</tr>`;
}

// --- Content components ---

export function sectionTitle(title: string): string {
  return `<tr>
  <td style="padding:20px 32px 8px;background:${colors.cardBg};">
    <h2 style="margin:0;font-size:16px;font-weight:700;color:${colors.text};border-bottom:2px solid ${colors.accent};padding-bottom:6px;display:inline-block;">${escapeHtml(title)}</h2>
  </td>
</tr>`;
}

export function statCardsRow(stats: Array<{ label: string; value: string; color?: string }>): string {
  const cellWidth = Math.floor(100 / stats.length);
  const cells = stats.map((s) => `
    <td width="${cellWidth}%" style="padding:8px;vertical-align:top;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${colors.bg};border-radius:6px;padding:12px;">
        <tr><td style="font-size:22px;font-weight:700;color:${s.color || colors.text};text-align:center;">${escapeHtml(s.value)}</td></tr>
        <tr><td style="font-size:11px;color:${colors.textMuted};text-align:center;padding-top:2px;">${escapeHtml(s.label)}</td></tr>
      </table>
    </td>
  `).join("");

  return `<tr>
  <td style="padding:12px 24px;background:${colors.cardBg};">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>${cells}</tr></table>
  </td>
</tr>`;
}

export function dataTable(
  columns: Array<{ label: string; align?: "left" | "right" | "center" }>,
  rows: string[][],
  maxRows = 10
): string {
  const headerCells = columns.map((c) =>
    `<th style="padding:8px 12px;text-align:${c.align || "left"};font-size:11px;font-weight:600;color:${colors.textMuted};text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid ${colors.border};">${escapeHtml(c.label)}</th>`
  ).join("");

  const displayRows = rows.slice(0, maxRows);
  const bodyRows = displayRows.map((row, i) => {
    const bg = i % 2 === 0 ? colors.cardBg : colors.bg;
    const cells = row.map((cell, j) =>
      `<td style="padding:8px 12px;text-align:${columns[j]?.align || "left"};font-size:13px;color:${colors.text};border-bottom:1px solid ${colors.border};background:${bg};">${cell}</td>`
    ).join("");
    return `<tr>${cells}</tr>`;
  }).join("");

  const truncated = rows.length > maxRows
    ? `<tr><td colspan="${columns.length}" style="padding:8px 12px;font-size:12px;color:${colors.textMuted};font-style:italic;">... and ${rows.length - maxRows} more</td></tr>`
    : "";

  return `<tr>
  <td style="padding:8px 32px 16px;background:${colors.cardBg};">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid ${colors.border};border-radius:6px;overflow:hidden;">
      <tr>${headerCells}</tr>
      ${bodyRows}
      ${truncated}
    </table>
  </td>
</tr>`;
}

export function horizontalBar(label: string, value: number, max: number, color: string): string {
  const pct = max > 0 ? Math.round((value / max) * 100) : 0;
  return `<tr>
  <td style="padding:3px 0;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      <tr>
        <td width="35%" style="font-size:12px;color:${colors.text};padding-right:8px;">${escapeHtml(label)}</td>
        <td width="50%">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${colors.bg};border-radius:3px;overflow:hidden;">
            <tr><td style="width:${pct}%;background:${color};height:14px;border-radius:3px;">&nbsp;</td><td>&nbsp;</td></tr>
          </table>
        </td>
        <td width="15%" style="font-size:12px;color:${colors.textMuted};text-align:right;padding-left:8px;">${escapeHtml(formatNum(value))}</td>
      </tr>
    </table>
  </td>
</tr>`;
}

export function barChart(items: Array<{ label: string; value: number; color?: string }>, title?: string): string {
  const max = Math.max(...items.map((i) => i.value), 1);
  const bars = items.map((item) =>
    horizontalBar(item.label, item.value, max, item.color || colors.accent)
  ).join("");

  return `${title ? sectionTitle(title) : ""}
<tr>
  <td style="padding:8px 32px 16px;background:${colors.cardBg};">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
      ${bars}
    </table>
  </td>
</tr>`;
}

export function textBlock(text: string): string {
  return `<tr>
  <td style="padding:12px 32px;background:${colors.cardBg};font-size:14px;line-height:1.6;color:${colors.text};">
    ${escapeHtml(text)}
  </td>
</tr>`;
}

export function recommendationRow(severity: "info" | "warning" | "critical", title: string, description: string): string {
  const severityColors = { info: colors.info, warning: colors.warning, critical: colors.danger };
  const severityLabels = { info: "INFO", warning: "WARNING", critical: "CRITICAL" };
  const color = severityColors[severity];

  return `<tr>
  <td style="padding:6px 32px;background:${colors.cardBg};">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-left:3px solid ${color};padding:10px 12px;background:${colors.bg};border-radius:0 4px 4px 0;">
      <tr>
        <td>
          <span style="font-size:10px;font-weight:700;color:${color};letter-spacing:0.5px;">${severityLabels[severity]}</span>
          <span style="font-size:13px;font-weight:600;color:${colors.text};padding-left:8px;">${escapeHtml(title)}</span>
        </td>
      </tr>
      <tr>
        <td style="padding-top:4px;font-size:12px;color:${colors.textMuted};line-height:1.5;">${escapeHtml(description)}</td>
      </tr>
    </table>
  </td>
</tr>`;
}

export function spacer(height = 8): string {
  return `<tr><td style="height:${height}px;background:${colors.cardBg};">&nbsp;</td></tr>`;
}

// --- Utilities ---

export function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function formatNum(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(1)}B`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toLocaleString();
}

export function formatBytes(bytes: number): string {
  if (bytes >= 1_000_000_000_000) return `${(bytes / 1_000_000_000_000).toFixed(1)} TB`;
  if (bytes >= 1_000_000_000) return `${(bytes / 1_000_000_000).toFixed(1)} GB`;
  if (bytes >= 1_000_000) return `${(bytes / 1_000_000).toFixed(1)} MB`;
  return `${(bytes / 1_000).toFixed(1)} KB`;
}
